#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config \
	external_bar off:40:0 \
	menubar_opacity 1.0 \
	mouse_follows_focus off \
	focus_follows_mouse off \
	display_arrangement_order default \
	window_origin_display default \
	window_placement second_child \
	window_insertion_point focused \
	window_zoom_persist off \
	window_shadow on \
	window_animation_duration 0.0 \
	window_animation_easing ease_out_circ \
	window_opacity_duration 0.0 \
	active_window_opacity 1.0 \
	normal_window_opacity 0.90 \
	window_opacity off \
	insert_feedback_color 0xff800a0a \
	split_ratio 0.50 \
	split_type auto \
	auto_balance off \
	top_padding 3 \
	bottom_padding 3 \
	left_padding 3 \
	right_padding 3 \
	window_gap 3 \
	layout bsp \
	mouse_modifier fn \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap

# yabai -m query --windows
yabai -m rule --add app="^(Calculator|Software Update|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|App Store|Activity Monitor|Finder)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add app="KakaoTalk" manage=off

echo "yabai configuration loaded.."
